# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VAR_determine_p <- function(x, pmax = 10L, criterion = 1L) {
    .Call(`_sparseVARboot_VAR_determine_p`, x, pmax, criterion)
}

determine_block_length <- function(x) {
    .Call(`_sparseVARboot_determine_block_length`, x)
}

gen_VAR <- function(u, ar, init, include_init = FALSE) {
    .Call(`_sparseVARboot_gen_VAR`, u, ar, init, include_init)
}

sim_mvn_chol <- function(Sigma, T) {
    .Call(`_sparseVARboot_sim_mvn_chol`, Sigma, T)
}

sim_VAR_cpp <- function(T, ar, Sigma, burn) {
    .Call(`_sparseVARboot_sim_VAR_cpp`, T, ar, Sigma, burn)
}

sim_VAR_cpp_both <- function(T, ar, Sigma, burn) {
    .Call(`_sparseVARboot_sim_VAR_cpp_both`, T, ar, Sigma, burn)
}

boot_means_R <- function(x, oracle_A, oracle_u, boot = 1L, p = 1L, l = 1L, abs_val = TRUE, q = 0.95 * ones(1), B = 9999L, show_progress = FALSE, penalization = 1L, nbr_lambdas = 10, lambda_ratio = 100, selection = 1L, eps = 0.001, pen_own = TRUE, only_lag1 = FALSE, c = 0.8, K = 15L, improvement_thresh = 0.01, Nsim = 1000L, alpha = 0.05) {
    .Call(`_sparseVARboot_boot_means_R`, x, oracle_A, oracle_u, boot, p, l, abs_val, q, B, show_progress, penalization, nbr_lambdas, lambda_ratio, selection, eps, pen_own, only_lag1, c, K, improvement_thresh, Nsim, alpha)
}

VAR_R <- function(y, p, intercept = TRUE) {
    .Call(`_sparseVARboot_VAR_R`, y, p, intercept)
}

sparseVAR_R <- function(Y, p, trim, pen, nbr_lambdas, lambda_ratio, eps, selection, c = 0.8, K = 15L, improvement_thresh = 0.01, Nsim = 1000L, alpha = 0.05, pen_own = TRUE, only_lag1 = FALSE) {
    .Call(`_sparseVARboot_sparseVAR_R`, Y, p, trim, pen, nbr_lambdas, lambda_ratio, eps, selection, c, K, improvement_thresh, Nsim, alpha, pen_own, only_lag1)
}

